FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app

FROM base AS builder
COPY pyproject.toml ./

RUN pip install --no-cache-dir .

FROM base AS prod
RUN adduser --disabled-password --gecos "" appuser

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
COPY src ./src

ENV PYTHONPATH=/app \
    ROOT_PATH="" \
    PORT=8000
EXPOSE 800

USER appuser
CMD ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port 8000"]
